### ISSUE TITLE
Model Prediction

### ISSUE THREAD

**Issue by lorenzomighie** [edouardelasalles/stnn#4]
Hello, I am running the code for a dataset (LOBO dataset) containing 7 time series of length 24888 in which each data has depth 8. 
My goal is to do regression, I would like to predict the evolution of each time series taking into consideration their spatial correlation. Even though during training the loss gets pretty low, the predicted values are pretty much constant and stay in the middle of the evolution of the ground truth, like a mean value. Do you have any idea why the prediction work so badly? 

I am using these parameters:
nz=80 mode=discover batch_size=200 dropout_f=0.05 dropout_d=0.125 lambd=1 lr=3e-3 nhid=8 nlayers=8 l1_rel=3e-6

**Comment by edouardelasalles** [comment]
Hi,
It seems that your are using a high number of layers and a large representation size. I would suggest to use only one our two layers for the dynamic function, and maybe reduce the size of the latent variables. Also, you are running the `discover` model, meaning that the model will try to learn spatial correlations by itself. If you already have some knowledge about the spatial correlations of your data, I would suggest to use the `refine` model.

**Comment by lorenzomighie** [comment]
Thank you for the advice, using the refine model things work better
