### ISSUE TITLE
heat_m dataset

### ISSUE THREAD

**Issue by Junting-Wang** [edouardelasalles/stnn#5]
Hello,

Your code looks great and is very helpful! Sorry if I miss any details, but could you please explain the heat_m dataset?

Thank you in advance for replying!

**Comment by edouardelasalles** [comment]
Hi,
The `heat_m` is dataset is a modified version of the `heat` dataset where heat is not diffused linearly. In this version, the heat diffusion is slower on the edges. You can find more details in the journal version of the paper.
